[theme]
primaryColor             = "#3B8BD4"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#F1EFE8"
textColor                = "#2C2C2A"
font                     = "sans serif"

[server]
headless   = true
enableCORS = false
port       = 8501