FROM python:3.11-slim

WORKDIR /app

ENV PYTHONPATH=/app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN mkdir -p data/raw data/processed reports

CMD ["bash", "-c", \
    "python src/ingestion/generate_data.py && \
     python src/ingestion/load_to_db.py && \
     streamlit run dashboard/app.py --server.port=8501 --server.address=0.0.0.0"]

EXPOSE 8501